services:
  deathcounter:
    image: roymond/deathcounter:latest
    env_file:
      - .env
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=container-dmz"
      - "traefik.http.routers.deathcounter.rule=Host(`deathcounter.roymond.net`)"
      - "traefik.http.routers.deathcounter.entrypoints=websecure"
      - "traefik.http.routers.deathcounter.tls.certresolver=production"
      - "traefik.http.services.deathcounter.loadbalancer.server.port=6200"
    restart: always

networks:
  container-dmz:
    external: true
