version: '3.8'

services:
  websocket:
    build:
      context: ./Server
      target: production
    expose:
      - "7654"
    container_name: deathcounter-wss-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=7654
    env_file:
      - ./Server/.env.production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:7654/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - deathcounter
    labels:
      # Enable Traefik
      - traefik.enable=true
      # HTTPS router
      - traefik.http.routers.websocket.rule=Host(`ws.roymond.net`)
      - traefik.http.routers.websocket.entrypoints=websecure
      - traefik.http.routers.websocket.tls.certresolver=production
      # Service configuration
      - traefik.http.services.websocket.loadbalancer.server.port=7654
      # WebSocket specific headers
      - traefik.http.routers.websocket.middlewares=websocket-headers
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket

networks:
  deathcounter:
    driver: bridge
